#!/usr/bin/env python3
"""Assemble the cursorduck.com website into _site/.

The site is plain HTML/CSS/JS without a framework, but it runs the real duck,
so it needs the engine files and the sounds from the extension next to it.
This script

  1. copies site/ to _site/,
  2. adds src/{models,render,effects,engine}.js, audio/ and icons/,
  3. writes _site/data.js with the version, the model/achievement/trick counts,
     the model names in both languages (from _locales/) and the German site
     strings (site/de.json),
  4. checks that every data-i18n key used in the HTML has a German string, that
     releases.json is well-formed and that its newest entry matches manifest.json.

Cloudflare Pages runs it as the build command with `_site` as the output
directory; locally it feeds the "site" preview server.
"""
import datetime
import json
import os
import re
import shutil
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SITE = os.path.join(ROOT, 'site')
OUT = os.path.join(ROOT, '_site')
ENGINE = ['models.js', 'render.js', 'effects.js', 'engine.js']


def read(*parts):
    with open(os.path.join(ROOT, *parts), encoding='utf-8') as f:
        return f.read()


def block(text, start, end='\n  ];'):
    """The source text between `start` and the next `end` (an array literal)."""
    i = text.index(start)
    j = text.index(end, i)
    return text[i:j]


def names_from(locale):
    msgs = json.loads(read('_locales', locale, 'messages.json'))
    out = {}
    for key, val in msgs.items():
        if key.startswith('model_'):
            out[key[6:].replace('_', '-')] = val['message']
    return out


def main():
    problems = []

    if os.path.isdir(OUT):
        shutil.rmtree(OUT)
    shutil.copytree(SITE, OUT)
    os.makedirs(os.path.join(OUT, 'src'))
    for name in ENGINE:
        shutil.copy(os.path.join(ROOT, 'src', name), os.path.join(OUT, 'src', name))
    shutil.copytree(os.path.join(ROOT, 'audio'), os.path.join(OUT, 'audio'))
    shutil.copytree(os.path.join(ROOT, 'icons'), os.path.join(OUT, 'icons'))
    os.remove(os.path.join(OUT, 'de.json'))   # bundled into data.js below

    manifest = json.loads(read('manifest.json'))
    models_js = read('src', 'models.js')
    popup_js = read('popup', 'popup.js')
    models = re.findall(r"^\s+id: '([a-z-]+)', name:", models_js, re.M)
    seasonal = len(re.findall(r"^\s+season: \{", models_js, re.M))
    hats = len(re.findall(r"kind: 'hat'", models_js))
    glasses = len(re.findall(r"kind: 'glasses'", models_js))
    achievements = len(re.findall(r"^\s+\['", block(popup_js, 'var ACHIEVEMENTS = ['), re.M))
    tricks = len(re.findall(r"\['[a-z]+', '", block(popup_js, 'var TRICKS = [')))

    names = {'en': names_from('en'), 'de': names_from('de')}
    for mid in models:
        for loc in ('en', 'de'):
            if mid not in names[loc]:
                problems.append('model %s has no name in _locales/%s' % (mid, loc))

    # The wishing pond needs a Turnstile site key. On Cloudflare it comes from the
    # build environment (TURNSTILE_SITE_KEY); without one the pond section stays
    # hidden. Locally the always-passing test key keeps the board testable.
    turnstile_key = os.environ.get('TURNSTILE_SITE_KEY', '')
    if not turnstile_key and not os.environ.get('CF_PAGES'):
        turnstile_key = '1x00000000000000000000AA'
    if not turnstile_key:
        print('note: TURNSTILE_SITE_KEY not set, the wishing pond stays hidden on this deployment')
    de = json.loads(read('site', 'de.json'))
    data = {
        'meta': {
            'version': manifest['version'],
            'models': len(models), 'seasonal': seasonal,
            'achievements': achievements, 'tricks': tricks,
            'hats': hats, 'glasses': glasses,
            'built': datetime.date.today().isoformat(),
            'turnstileSiteKey': turnstile_key
        },
        'names': names,
        'de': de
    }
    with open(os.path.join(OUT, 'data.js'), 'w', encoding='utf-8') as f:
        f.write('/* generated by tools/site_build.py */\nwindow.CD_DATA = '
                + json.dumps(data, ensure_ascii=False, separators=(',', ':')) + ';\n')

    # i18n parity: every key in the markup needs a German string
    used = set()
    for fn in os.listdir(SITE):
        if fn.endswith('.html'):
            used.update(re.findall(r'data-i18n(?:-ph|-content)?="([^"]+)"', read('site', fn)))
    missing = sorted(used - set(de['dom']))
    unused = sorted(set(de['dom']) - used)
    if missing:
        problems.append('German strings missing for: ' + ', '.join(missing))
    if unused:
        print('note: German strings not used in any page: ' + ', '.join(unused))
    js_keys = set()
    for fn in os.listdir(SITE):
        if fn.endswith('.js') and 'var STR_EN = {' in read('site', fn):
            js_keys.update(re.findall(r"^\s{4}([A-Za-z_0-9]+): '",
                                      block(read('site', fn), 'var STR_EN = {', '\n  };'), re.M))
    js_missing = sorted(js_keys - set(de['js']))
    if js_missing:
        problems.append('German JS strings missing for: ' + ', '.join(js_missing))

    releases = json.loads(read('site', 'releases.json'))
    for r in releases:
        for k in ('version', 'date', 'title', 'items'):
            if k not in r:
                problems.append('release %s lacks "%s"' % (r.get('version', '?'), k))
        if len(r.get('items', {}).get('en', [])) != len(r.get('items', {}).get('de', [])):
            problems.append('release %s: en/de item count differs' % r.get('version', '?'))
    if releases and releases[0]['version'] != manifest['version']:
        problems.append('releases.json starts with %s but manifest.json says %s '
                        '(add the new release to the duck log)' % (releases[0]['version'], manifest['version']))

    if problems:
        for p in problems:
            print('ERROR: ' + p)
        sys.exit(1)

    size = sum(os.path.getsize(os.path.join(dp, f)) for dp, _, fs in os.walk(OUT) for f in fs)
    print('cursorduck.com %s: %d models (%d seasonal), %d achievements, %d trick buttons, '
          '%d hats, %d glasses -> _site/ (%d KB)'
          % (manifest['version'], len(models), seasonal, achievements, tricks, hats, glasses, size // 1024))


if __name__ == '__main__':
    main()
